framework:
    secret: '%env(APP_SECRET)%'
    validation: { enable_annotations: true }
    

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true
