parameters:

services:

    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
          $userPhotoDir: "%kernel.project_dir%/public/images/uploads/users"
          $figurePhotoDir: "%kernel.project_dir%/public/images/uploads/figures"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    AppBundle\DataFixtures\Provider\HashPasswordProvider:
        tags: [ { name: nelmio_alice.faker.provider } ]

    AppBundle\DataFixtures\Provider\ImageProvider:
        tags: [ { name: nelmio_alice.faker.provider } ]

    App\EntityListener\FigureEntityListener:
      tags:
        - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Figure'}
        - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Figure'}
    

