parameters:

services:

    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
          $userPhotoDir: "%kernel.project_dir%/public/images/uploads/users"
          $figurePhotoDir: "%kernel.project_dir%/public/images/uploads/figures"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    AppBundle\DataFixtures\Provider\HashPasswordProvider:
        tags: [ { name: nelmio_alice.faker.provider } ]
    

